### ISSUE TITLE
potato.js working differently than needed

### ISSUE THREAD

**Issue by kaukokolka** [pixelmasters/sandbox#1]
Potatoes are more important!!!! >:(

**Comment by cyf-4** [comment]
Your problem should now be fixed. Have a great day!

**Comment by kaukokolka** [comment]
@karlisb2  IT ISN'T FIXED. IMM ANGERRY!?

**Comment by kaukokolka** [comment]
@karlisb2 oh nevermind. Thank you for your waste of time! >:-)

**Comment by kaukokolka** [comment]
@karlisb2 oh nevermind. Thank you for your waste of time! >:-)
